# Variables de entorno

name: Ejemplo de Composite Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel step
        run: |
          echo "Valor -> $MY_VAR $STEP_MY_VAR"
          echo "         ${{ vars.MY_VAR_REPO_1 }}"
