name: Hola Mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hello, World!"
      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola World!" > hola.txt
      
      - name: Read file
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest

    steps:
      - name: ls
        run: ls -la
