name: Hola Mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hello, World!"

      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola World!" > hola.txt

      - name: Read file
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: ls
        run: ls -la

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: latest

      - name: node version
        run: node --version

      - name: setup PHP
        uses: shivammathur/setup-php@2.35.5
        with:
          php-version: '8.3'

      - name: PHP version
        run: php --version
      

